apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zat3il8kp-go 
  janus-idp.io/tekton: zat3il8kp-go
  backstage.io/kubernetes-id: zat3il8kp-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zat3il8kp-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml