apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zat3il8kp-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zat3il8kp-go 
  name: zat3il8kp-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zat3il8kp-go 
